package org.apache.cordova;

public enum Status {
  CLASS_NOT_FOUND_EXCEPTION, ERROR, ILLEGAL_ACCESS_EXCEPTION, INSTANTIATION_EXCEPTION, INVALID_ACTION, IO_EXCEPTION, JSON_EXCEPTION, MALFORMED_URL_EXCEPTION, NO_RESULT, OK;
  
  static {
    CLASS_NOT_FOUND_EXCEPTION = new Status("CLASS_NOT_FOUND_EXCEPTION", 2);
    ILLEGAL_ACCESS_EXCEPTION = new Status("ILLEGAL_ACCESS_EXCEPTION", 3);
    INSTANTIATION_EXCEPTION = new Status("INSTANTIATION_EXCEPTION", 4);
    MALFORMED_URL_EXCEPTION = new Status("MALFORMED_URL_EXCEPTION", 5);
    IO_EXCEPTION = new Status("IO_EXCEPTION", 6);
    INVALID_ACTION = new Status("INVALID_ACTION", 7);
    JSON_EXCEPTION = new Status("JSON_EXCEPTION", 8);
    ERROR = new Status("ERROR", 9);
    $VALUES = new Status[] { NO_RESULT, OK, CLASS_NOT_FOUND_EXCEPTION, ILLEGAL_ACCESS_EXCEPTION, INSTANTIATION_EXCEPTION, MALFORMED_URL_EXCEPTION, IO_EXCEPTION, INVALID_ACTION, JSON_EXCEPTION, ERROR };
  }
}


/* Location:              C:\Users\Root1\Desktop\Stash\output\!\org\apache\cordova\PluginResult$Status.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */